title: Alliedbusiness
description: We specialize in developing Teams AI bots that empower organizations to boost productivity and efficiency by harnessing the power of artificial intelligence.

url: https://service.alliedbusiness.jp
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: "" # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: About
      url: /about
    - title: Service
      url: /service
    - title: Privacy
      url: /privacy
    - title: Sign in
      url: https://ta1010.alliedbusiness.jp
    - title: Sign up
      url: https://ta1010.alliedbusiness.jp/#/register

social:
    github: terateams
    # twitter: brianmaierjr
    # facebook: brianmaierjr
    # email: brimaidesigns@gmail.com
    # linkedin: brianmaierjr
    # youtube: RickAstleyYT
    # tumblr: i-am-a-fish

# google_analytics: "UA-58263416-1"

# disqus:
#     shortname: brianmaierjr
